
#
# olsr.org makefile
# $Id: Makefile,v 1.9 2004/10/19 22:13:21 kattemat Exp $
#

CC ?= gcc

CFLAGS ?= -Isrc -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -g #-pg -DDEBUG #-march=i686
LIBS = -lpthread -lm -ldl
INSTALL_PREFIX ?=
STRIP ?= strip
BISON ?= bison
FLEX ?= flex
CFGDIR = src/cfgparser

DEPFILE = .linux-depend
DEPEND= makedepend -Dlinux -Y -f $(DEPFILE) -- $(CFLAGS)

SRCS= $(wildcard src/*.c) \
      $(wildcard src/linux/*.c) \
      $(wildcard src/cfgparser/*.c)

HDRS= $(wildcard src/*.h) \
      $(wildcard src/linux/*.h) \
      $(wildcard src/cfgparser/*.h)

OBJS= $(patsubst %.c,%.o,$(wildcard src/*.c)) \
      $(patsubst %.c,%.o,$(wildcard src/linux/*.c)) \
      $(patsubst %.c,%.o,$(wildcard src/cfgparser/*.c))


all:	olsrd

olsrd:	$(OBJS)
	$(CC) $(LIBS) -o bin/$@ $(OBJS)

depend:
	rm -f $(DEPFILE)
	make $(DEPFILE)


$(DEPFILE):
	@echo '# olsrd dependency file. AUTOGENERATED' > $(DEPFILE)
	$(DEPEND) -- $(SRCS) >&/dev/null


$(CFGDIR)/oparse.c: $(CFGDIR)/oparse.y $(CFGDIR)/olsrd_conf.h
	$(BISON) -d -o$(CFGDIR)/oparse.c $(CFGDIR)/oparse.y

$(CFGDIR)/oparse.h: $(CFGDIR)/oparse.c


$(CFGDIR)/oscan.c: $(CFGDIR)/oscan.lex $(CFGDIR)/oparse.h $(CFGDIR)/olsrd_conf.h
	$(FLEX) -o$(CFGDIR)/oscan.c $(CFGDIR)/oscan.lex

libs: 
	for i in lib/*; do \
		$(MAKE) -C $$i; \
	done; 

clean_libs: 
	for i in lib/*; do \
		$(MAKE) -C $$i clean; \
	done; 

.PHONY: clean
clean:
	-rm -f $(OBJS) $(DEPFILE)

install_libs:
	for i in lib/*; do \
		$(MAKE) -C $$i LIBDIR=$(INSTALL_PREFIX)/usr/lib install; \
	done; 	


install_bin:
	$(STRIP) bin/olsrd
	install -D -m 755 bin/olsrd $(INSTALL_PREFIX)/usr/sbin/olsrd

install: install_bin
	@echo olsrd uses the configfile $(INSTALL_PREFIX)/etc/olsr.conf
	@echo a default configfile. A sample configfile
	@echo can be installed
	mkdir -p $(INSTALL_PREFIX)/etc
	cp -i files/olsrd.conf.default $(INSTALL_PREFIX)/etc/olsrd.conf
	@echo -------------------------------------------
	@echo Edit $(INSTALL_PREFIX)/etc/olsrd.conf before running olsrd!!
	@echo -------------------------------------------
	mkdir -p $(INSTALL_PREFIX)/usr/share/man/man8/
	cp files/olsrd.8.gz $(INSTALL_PREFIX)/usr/share/man/man8/olsrd.8.gz


sinclude $(DEPFILE)
