#
# LINUX SPECIFIC CONFIGURATION
#

INSTALL_PREFIX ?=
LIBDIR =	$(INSTALL_PREFIX)/usr/lib

SRCS += 	$(wildcard src/linux/*.c) $(wildcard src/unix/*.c)
HDRS +=		$(wildcard src/linux/*.h) $(wildcard src/unix/*.h)

DEFINES = 	-Dlinux
LIBS =		-lm -ldl

PLUGIN_FULLNAME ?= $(PLUGIN_NAME).so.$(PLUGIN_VER)
INSTALL_LIB =	install -D -m 755 $(PLUGIN_FULLNAME) $(LIBDIR)/$(PLUGIN_FULLNAME); \
		/sbin/ldconfig -n $(LIBDIR)
		
OS_PTHREAD = -lpthread